# Generated by Django 3.2.12 on 2024-12-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_productosssss2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productosssss2',
        ),
    ]
