# Generated by Django 3.2.12 on 2024-12-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_delete_productosssss2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default=None, upload_to='productos_imagenes/'),
            preserve_default=False,
        ),
    ]
