# Generated by Django 3.2.12 on 2024-12-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Semi-nuevo'), (3, 'Buen estado'), (4, 'Usado')], default=1),
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
    ]
